# site settings
title: C4 Arquitetura
subtitle: por Cláudia Capuano
email: aricneto@gmail.com
description: Um lar deve ter a cara do seu dono,<br /> o seu não deve ser diferente.
baseurl: "" # the subpath of your site, e.g. /blog
url: www.c4arquitetura.com
author:
street_address: Rua Marechal Rondon, nº146
city: Casa Forte, Recife
state: PE
zip_code: 52061-050
country: Brasil
phone: (81) 99126-6507

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://facebook.com/c4arquitetura
youtube_url: https://www.youtube.com/channel/UCf82sTh64qSyxQeu4JvLaaQ/videos
wordpress_url: http://c4arquitetura.com.br/blog/
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/c4arquitetura
linkedin_url: 
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
